export const CATEGORY_TYPES = {
  INCOME: "INCOME",
  OUTCOME: "OUTCOME",
};

export const TRANSACTION_TYPES = {
  INCOME: "INCOME",
  EXPENCE: "EXPENCE",
  TRANSFER: "TRANSFER",
  ADJUSTMENT: "ADJUSTMENT",
};
